### ISSUE TITLE
正则匹配问题

### ISSUE THREAD

**Issue by zljaaa** [bes2008/sqlhelper#203]
com.jn.sqlhelper.common.utils.SQLs中
isSelectCountStatement方法匹配sql的正则private static final Pattern SELECT_COUNT_PATTERN = Pattern.compile("select\\s+count.*");
如果sql为select county from xxxx 。会匹配到

**Comment by bes2008** [comment]
在4.0.8 版本修复了

**Comment by bes2008** [comment]
在4.0.8 版本修复了
