### ISSUE TITLE
新版本的仓库在哪里？没有找到

### ISSUE THREAD

**Issue by zljaaa** [bes2008/sqlhelper#204]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bes2008** [comment]
```xml
<dependency>
    <groupId>io.github.bes2008.solution.sqlhelper</groupId>
    <artifactId>sqlhelper</artifactId>
    <version>4.0.8</version>
</dependency>
```

把 groupId 统一调整为io.github.bes2008.solution.XXX即可。
例如sqlhelper的调整为io.github.bes2008.solution.sqlhelper
例如langx的调整为io.github.bes2008.solution.langx
