### ISSUE TITLE
分页带total 的bug重现

### ISSUE THREAD

**Issue by ocean-zhc** [bes2008/sqlhelper#212]
**Describe the bug**
拼接的sql不具有通用性

**To Reproduce**
用户xml输入的sql：
select * from tab1 --查询sql

这拼接出来的 就会把后面的:--->)tmp_count 当成注释了？

```sql
select count(1) from (select * from tab1 -- 查询sql) tmp_count
```

那么jdbc 实际执行的sql 就是 如下：
select count(1) from (select * from tab1
很明显是错误的sql，，改源码也挺简单，我不改源码直接把sql注释去掉即可。。
<img width="853" alt="image" src="https://github.com/user-attachments/assets/ad43cd24-8963-46ce-9278-9e814db3b8bb">

修改建议：
<img width="1844" alt="image" src="https://github.com/user-attachments/assets/ec09ed91-45c8-41da-bd3c-636d879a2645">
```java
"select count(" + countColumn + ") from (" + originalSql + ") tmp_count";
```

调整为：
" + originalSql + " 左右加上换行符
```java
"select count(" + countColumn + ") from ("\n" + originalSql + "\n") tmp_count";
```

同类问题 可以参照修改

另外：如果不修改，问题也不大，用户不加注释即可，或者不在末尾加注释即可。

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bes2008** [comment]
这个没有必要修改。使用时，不要将注释传入。
